### ISSUE TITLE
Should removeNode trigger onUnSelected?

### ISSUE THREAD

**Issue by bjaanes** [zTree/zTree_v3#107]
I am using the onUnSelected to update a context menu, but when I delete node from the tree, the context menu doesn't get updated properly. 

Should onUnSelected be triggered after removeNode has finished?

Perhaps with null/undefined as the treeNode?

**Comment by zTree** [comment]
please pull the latest code from github.  I have change code for you.

Now , when you remove the node which be selected,  zTree will trigger the 'onUnSelected' callback.

But please change your code, because I have change the parameters in 'onSelected' and 'onUnSelected' callback.  I remove the 'event'.

E.g.    onSelected(treeId, node)      onUnSelected(treeId, node)

**Comment by bjaanes** [comment]
That is fantastic, thank you! Is it possible to create a new minor version in github as well, so that I can pull it in with bower too? :) :+1:
