### ISSUE TITLE
not naming files with version number 

### ISSUE THREAD

**Issue by maruilian11** [zTree/zTree_v3#130]
hi, recently we want to add your lib on https://cdnjs.com, could you please consider modifying filename from `jquery.ztree.core-3.5.js` to `jquery.ztree.core.js`.
thank you very much!

https://github.com/cdnjs/cdnjs/issues/6816

**Comment by zTree** [comment]
I don't know how do you add jQuery to cdnjs.com?   The jQuery's js files have the version. (like: http://code.jquery.com/jquery-2.2.0.js)  

By the way,  I will not add this version(3.5) to zTree_v3.  so, if you want to add, you can modify filename by yourself

**Comment by maruilian11** [comment]
hi, we use npm auto-update to add jquery's files, the package has a dist folder with `jquery.js`, `jquery.min.js` and `jquery.min.map`.

we will consider to add pre-versions manually, thank you!

**Comment by maruilian11** [comment]
sorry, I forgot to mention that we want to modify the filename because we want to use **git auto-update** depended on git tags.

**Comment by PeterDaveHello** [comment]
Hi @zTree, 

Thanks for reply, I'm Peter from **cdnjs**, **cdnjs** is a free and open source public web library CDN service, actually there is a hosting request from a **zTree** user in issue https://github.com/cdnjs/cdnjs/issues/6816, and **zTree** looks good to be hosted on **cdnjs**, we can help the web developers and web masters using **zTree** to load the resources faster, and save their bandwidth, also can help spread this awesome library, the only problem is the filenames containing version number is actually a bad implement of general purpose CDN service, as you can see, the most famous web library cdn - **[Google CDN](https://developers.google.com/speed/libraries/)** hosts files without version number in filename, jquery uses version number in the filename because they only host their jQuery under the same folder, but we host about 1.8k libraries, that's impossible for us, we just use the directory name to server different versions of libraries, yes we can modify filename by ourself this time, for all the already released versions, but for a long-term support, we want the new versions of every lib can be automatically pulled, it'll be a hard-work to do it if all there are version numbers in the filenames, so I'll respectfully suggest you to consider if this is possible in **zTree**, but anyway, I'll totally respect your dicission, thank you very much!

**Comment by zTree** [comment]
I understand. I'll modify filename with this week.

**Comment by PeterDaveHello** [comment]
> I understand. I'll modify filename with this week.

Thanks a lot @zTree :smile:

**Comment by zTree** [comment]
I have modified filename. please check it.

**Comment by PeterDaveHello** [comment]
Thanks @zTree
