### ISSUE TITLE
Checkbox not correct checked by initial state in hierarchy

### ISSUE THREAD

**Issue by ZhukDmitry** [zTree/zTree_v3#441]
Hi.
Is it any method to synchronize checkboxes in hierarchy with initial checked state?
If you check your demo for checkboxes.
- can check 2 - initial checked
- can check 2-2 - no initial state
- can check 2-2-1 - initial checked

And as result check-2-2 gray (half check) but there is no check symbol

Thanks for your job!

**Comment by zTree** [comment]
I don't understand your detail requirement. 

If you initial checked the node '2', but the node '2-2' have not be add to zTree, please see the 'setting.async.dataFilter'  or set the node '2-2' data by your self.

**Comment by ZhukDmitry** [comment]
Check your demos.
[http://www.treejs.cn/v3/demo.php#_201](url)
As you can see 
- checked 2 (level 0)
- unchecked 2-2 (but grey, kevel 1)
- checked 2-2-1 (level 3)

And I want to call some method to fix it

**Comment by zTree** [comment]
If you don't allow '2-2' be unchecked in your project, you need to checked '2-2' when user checked '2-2-1'. 

You should not to fix the node data when init zTree.

**Comment by ZhukDmitry** [comment]
Lets explain on your demo images
What I get by default
![2020-02-13_14-03-06-current](https://user-images.githubusercontent.com/18059939/74428357-e5134780-4e69-11ea-8d4d-95a6ef2a24f4.png)
What I expect - just click tiwce on leaf (2-2-1)
![2020-02-13_14-03-19-expect](https://user-images.githubusercontent.com/18059939/74428377-ee041900-4e69-11ea-8c10-993771791708.png)

I mean middle checkbox is not set into half checked

And I want to call method to fix this. Of you can fix it as bug

**Comment by lexeek** [comment]
Hi! I faced the same wrong behavior. The checkbox icon (v) does not get visible if the tree was initialized with the nodes which some of them has isChecked property as true

**Comment by zTree** [comment]
@lexeek 
I guess you use the async method to add nodes.  In zTree, it will don't check the parent node when add it's childnodes which has checked. 

because when you don't add childe nodes, the  parent node will don't know whether it should be checked. And if zTree auto fixed the parent node when add nodes,  it looks a little strange ......... at first the parent node hasn't be checked, but when you expand it to add childNodes, it will be checked.

so you should checked the parent node before it add childnodes. because you should know the  parent node whether it should be checked.

**Comment by lexeek** [comment]
@zTree I got your point with async method.
But, I don't add nodes with this one. I am initializing the tree with the list of nodes and each node has an attributes like 'open' and 'checked'  (true or false) it very similar to your example - [Checkbox count](http://www.treejs.cn/v3/demo/en/excheck/checkbox_count.html)
Just have look at this example and could you explain why some of the nodes don't have checkboxes. Instead of having checkboxes with grayed background these nodes just have grayed boxes
![image](https://user-images.githubusercontent.com/1452043/91421736-f4367180-e85e-11ea-9c7e-e351be754715.png)

In case when I initialize tree with nodes I expect that nodes which have some children selected must also have checkboxes something like on the screenshot below
![image](https://user-images.githubusercontent.com/1452043/91422719-357b5100-e860-11ea-8111-aae32c547b89.png)

**Comment by zTree** [comment]
I understand your needs.

But your needs are not completely suitable for everyone, so zTree does not make any corrections to the initialized data, please ensure that your initialized data is accurate

@lexeek
